apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-minio
spec:
  serviceName: {{ .Release.Name }}-minio
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-minio
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.minio.repository }}:{{ .Values.image.minio.tag }}"
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources.minio | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.minio.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
spec:
  type: {{ .Values.service.minio.type }}
  selector:
    app: {{ .Release.Name }}-minio
  ports:
    - name: api
      port: {{ .Values.service.minio.apiPort }}
      targetPort: 9000
    - name: console
      port: {{ .Values.service.minio.consolePort }}
      targetPort: 9001
